title: Publications
modelClass: Katana\Publications\Models\Publications
list: $/katana/publications/models/publications/columns.yaml
recordUrl: 'katana/publications/publications/update/:id'
noRecordsMessage: 'backend::lang.list.no_records'
showSetup: true
showCheckboxes: true
toolbar:
    buttons: list_toolbar
    search:
        prompt: 'backend::lang.list.search_prompt'
